//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Vnb_IPM_2017.Module.BusinessObjects
{

    public partial class NhanVien : XPObject
    {
        string fTenDayDu;
        [DevExpress.Xpo.DisplayName(@"Tên đầy đủ")]
        public string TenDayDu
        {
            get { return fTenDayDu; }
            set { SetPropertyValue<string>("TenDayDu", ref fTenDayDu, value); }
        }
        string fNgaySinh;
        [DevExpress.Xpo.DisplayName(@"Ngày sinh")]
        public string NgaySinh
        {
            get { return fNgaySinh; }
            set { SetPropertyValue<string>("NgaySinh", ref fNgaySinh, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>("DiaChi", ref fDiaChi, value); }
        }
        string fSoDienThoai;
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>("SoDienThoai", ref fSoDienThoai, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        string fChucVu;
        [DevExpress.Xpo.DisplayName(@"Chức vụ")]
        public string ChucVu
        {
            get { return fChucVu; }
            set { SetPropertyValue<string>("ChucVu", ref fChucVu, value); }
        }
        string fNgayVaoLam;
        [DevExpress.Xpo.DisplayName(@"Ngày vào làm")]
        public string NgayVaoLam
        {
            get { return fNgayVaoLam; }
            set { SetPropertyValue<string>("NgayVaoLam", ref fNgayVaoLam, value); }
        }
        string fNgayThoiViec;
        [DevExpress.Xpo.DisplayName(@"Ngày thôi việc")]
        public string NgayThoiViec
        {
            get { return fNgayThoiViec; }
            set { SetPropertyValue<string>("NgayThoiViec", ref fNgayThoiViec, value); }
        }
        PhongBan fPhongBan;
        [Association(@"NhanVienReferencesPhongBan")]
        [DevExpress.Xpo.DisplayName(@"Phòng ban")]
        public PhongBan PhongBan
        {
            get { return fPhongBan; }
            set { SetPropertyValue<PhongBan>("PhongBan", ref fPhongBan, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Hạng mục dự án")]
        [Association(@"HangMucDuAnReferencesNhanVien")]
        public XPCollection<HangMucDuAn> HangMucDuAns { get { return GetCollection<HangMucDuAn>("HangMucDuAns"); } }
        [DevExpress.Xpo.DisplayName(@"Dự án")]
        [Association(@"DuAnReferencesNhanVien")]
        public XPCollection<DuAn> DuAns { get { return GetCollection<DuAn>("DuAns"); } }
        [DevExpress.Xpo.DisplayName(@"Hồ sơ dự thầu")]
        [Association(@"HoSoDuThauReferencesNhanVien")]
        public XPCollection<HoSoDuThau> HoSoDuThaus { get { return GetCollection<HoSoDuThau>("HoSoDuThaus"); } }
    }

}
