//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;

namespace Vnb_IPM_2017.Module.BusinessObjects
{

    public partial class FleAttachments : XPLiteObject
    {
        long fOid;
        [Key(true)]
        [VisibleInDetailView(false), VisibleInListView(false)]
        public long Oid
        {
            get { return fOid; }
            set { SetPropertyValue<long>("Oid", ref fOid, value); }
        }
    }

}
