//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Vnb_IPM_2017.Module.BusinessObjects
{

    public partial class HinhThucThanhToan : XPObject
    {
        string fTieuDe;
        [DevExpress.Xpo.DisplayName(@"Tiêu đề")]
        public string TieuDe
        {
            get { return fTieuDe; }
            set { SetPropertyValue<string>("TieuDe", ref fTieuDe, value); }
        }
    }

}
