//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Vnb_IPM_2017.Module.BusinessObjects
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class HopDong : FleAttachments
    {
        string fSoHopDong;
        [Indexed(Name = @"sohd_idx")]
        [DevExpress.Xpo.DisplayName(@"Số hợp đồng")]
        public string SoHopDong
        {
            get { return fSoHopDong; }
            set { SetPropertyValue<string>("SoHopDong", ref fSoHopDong, value); }
        }
        string fTenHopDong;
        [Indexed(Name = @"tenhd_idx")]
        [DevExpress.Xpo.DisplayName(@"Tên hợp đồng")]
        public string TenHopDong
        {
            get { return fTenHopDong; }
            set { SetPropertyValue<string>("TenHopDong", ref fTenHopDong, value); }
        }
        DuAn fDuAn;
        [Indexed(Name = @"duan_idx")]
        [DevExpress.Xpo.DisplayName(@"Dự án")]
        public DuAn DuAn
        {
            get { return fDuAn; }
            set { SetPropertyValue<DuAn>("DuAn", ref fDuAn, value); }
        }
        GoiThau fGoiThau;
        [DevExpress.Xpo.DisplayName(@"Gói thầu")]
        public GoiThau GoiThau
        {
            get { return fGoiThau; }
            set { SetPropertyValue<GoiThau>("GoiThau", ref fGoiThau, value); }
        }
        DateTime fNgayKy;
        [DevExpress.Xpo.DisplayName(@"Ngày ký")]
        public DateTime NgayKy
        {
            get { return fNgayKy; }
            set { SetPropertyValue<DateTime>("NgayKy", ref fNgayKy, value); }
        }
        DateTime fNgayHieuLuc;
        [DevExpress.Xpo.DisplayName(@"Ngày hiệu lực")]
        public DateTime NgayHieuLuc
        {
            get { return fNgayHieuLuc; }
            set { SetPropertyValue<DateTime>("NgayHieuLuc", ref fNgayHieuLuc, value); }
        }
        HinhThucThanhToan fHinhThucThanhToan;
        [DevExpress.Xpo.DisplayName(@"Hình thức thanh toán")]
        public HinhThucThanhToan HinhThucThanhToan
        {
            get { return fHinhThucThanhToan; }
            set { SetPropertyValue<HinhThucThanhToan>("HinhThucThanhToan", ref fHinhThucThanhToan, value); }
        }
        double fGiaTriHD;
        [DevExpress.Xpo.DisplayName(@"Giá trị hợp đồng")]
        public double GiaTriHD
        {
            get { return fGiaTriHD; }
            set { SetPropertyValue<double>("GiaTriHD", ref fGiaTriHD, value); }
        }
        int fThoiGianThucHien;
        [DevExpress.Xpo.DisplayName(@"Thời gian thực hiện")]
        public int ThoiGianThucHien
        {
            get { return fThoiGianThucHien; }
            set { SetPropertyValue<int>("ThoiGianThucHien", ref fThoiGianThucHien, value); }
        }
        DateTime fNgayHetHan;
        [DevExpress.Xpo.DisplayName(@"Ngày hết hạn")]
        public DateTime NgayHetHan
        {
            get { return fNgayHetHan; }
            set { SetPropertyValue<DateTime>("NgayHetHan", ref fNgayHetHan, value); }
        }
        NhaDauTu fDoiTac;
        [Indexed(Name = @"doitac_idx")]
        [Association(@"HopDongReferencesNhaDauTu")]
        [DevExpress.Xpo.DisplayName(@"Đối tác")]
        public NhaDauTu DoiTac
        {
            get { return fDoiTac; }
            set { SetPropertyValue<NhaDauTu>("DoiTac", ref fDoiTac, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Thanh toán hợp đồng")]
        [Association(@"ThanhToanReferencesHopDong")]
        public XPCollection<ThanhToan> ThanhToans { get { return GetCollection<ThanhToan>("ThanhToans"); } }
    }

}
