//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Vnb_IPM_2017.Module.BusinessObjects
{

    public partial class NhaDauTu : XPObject
    {
        string fTenDayDu;
        [Indexed(Name = @"ten_idx")]
        [DevExpress.Xpo.DisplayName(@"Tên đầy đủ")]
        public string TenDayDu
        {
            get { return fTenDayDu; }
            set { SetPropertyValue<string>("TenDayDu", ref fTenDayDu, value); }
        }
        string fDiaChi;
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>("DiaChi", ref fDiaChi, value); }
        }
        string fMST;
        [Indexed(Name = @"mst_idx")]
        public string MST
        {
            get { return fMST; }
            set { SetPropertyValue<string>("MST", ref fMST, value); }
        }
        string fSoDienThoai;
        [DevExpress.Xpo.DisplayName(@"Số điện thoại")]
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>("SoDienThoai", ref fSoDienThoai, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fWebsite;
        public string Website
        {
            get { return fWebsite; }
            set { SetPropertyValue<string>("Website", ref fWebsite, value); }
        }
        string fDaiDien;
        [DevExpress.Xpo.DisplayName(@"Đại diện")]
        public string DaiDien
        {
            get { return fDaiDien; }
            set { SetPropertyValue<string>("DaiDien", ref fDaiDien, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Hồ sơ dự thầu")]
        [Association(@"HoSoDuThauReferencesNhaDauTu")]
        public XPCollection<HoSoDuThau> HoSoDuThaus { get { return GetCollection<HoSoDuThau>("HoSoDuThaus"); } }
        [DevExpress.Xpo.DisplayName(@"Hợp đồng")]
        [Association(@"HopDongReferencesNhaDauTu")]
        public XPCollection<HopDong> HopDongs { get { return GetCollection<HopDong>("HopDongs"); } }
    }

}
