//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.ExpressApp.Model;

namespace Vnb_IPM_2017.Module.BusinessObjects
{

    [DevExpress.Persistent.Base.DefaultClassOptions]
    public partial class ThanhToan : XPObject
    {
        double fNgayThanhToan;
        [DevExpress.Xpo.DisplayName(@"Ngày Thanh toán")]
        public double NgayThanhToan
        {
            get { return fNgayThanhToan; }
            set { SetPropertyValue<double>("NgayThanhToan", ref fNgayThanhToan, value); }
        }
        HopDong fHopDong;
        [Association(@"ThanhToanReferencesHopDong")]
        [DevExpress.Xpo.DisplayName(@"Hợp đồng")]
        public HopDong HopDong
        {
            get { return fHopDong; }
            set { SetPropertyValue<HopDong>("HopDong", ref fHopDong, value); }
        }
        string fGiaTriThanhToan;
        [DevExpress.Xpo.DisplayName(@"Số tiền")]
        public string GiaTriThanhToan
        {
            get { return fGiaTriThanhToan; }
            set { SetPropertyValue<string>("GiaTriThanhToan", ref fGiaTriThanhToan, value); }
        }
        HinhThucThanhToan fHinhThucThanhToan;
        [DevExpress.Xpo.DisplayName(@"Hình thức thanh toán")]
        [ModelDefault("PropertyEditorType", "Vnb_IPM_2017.Module.Web.PropertyEditors.OMWebLookupEditor")]
        public HinhThucThanhToan HinhThucThanhToan
        {
            get { return fHinhThucThanhToan; }
            set { SetPropertyValue<HinhThucThanhToan>("HinhThucThanhToan", ref fHinhThucThanhToan, value); }
        }
    }

}
